name: taskom
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.6
  day_night_time_picker: ^1.1.3
  msh_checkbox: ^2.0.1
  simple_circular_progress_bar: ^1.0.2
  shamsi_date: ^1.0.1
  scroll_to_index: ^3.0.1
  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  provider: ^6.0.3
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  dartz: ^0.10.1
  get_it: ^7.2.0
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Shabnam
      fonts:
        - asset: fonts/ShabnamMedium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
